site_name: Портфолио Никиты Кондрата
site_url: https://nikitakondrat.github.io/
site_description: "Студент ИТМО"
site_author: Никита Кондрат

docs_dir: .

nav:
  - Main page: index.md
  - About author: about.md
  - Labworks 2 semester:
      - labwork 1 Tutorial: labwork1.md
      - labwork 2 Tutorial: labwork2.md

theme:
  name: simple-blog
  author: Никита Кондрат

repo_url: https://github.com/NikitaKondrat/
repo_name: NikitaKondrat/

plugins:
  - search:
      lang: ["ru"]
      separator: '[\s\-]+'