name: Deploy MkDocs Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy docs
        run: mkdocs gh-deploy --force --config-file src/mkdocs.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}